In [ ]:
#Created and saves the dataset
#Saves me from loading dataset from folder each training session(takes approximately 4 minutes)

In [1]:
import tensorflow as tf

In [2]:
import sys 
sys.path.insert(0, 'F:\messy code\\afg ordered\second generation')
import data

In [34]:
#returns the paths of images that belong to games published after 2004
def paths(img_dir):
    img_paths = data.dir_to_list(img_dir)
    result = []
    dates = data.dates_directory("F:\messy code\\afg ordered\second generation\image_collecting\getchu\data.txt")
    for path in img_paths: 
        name = data.path_to_name(path)
        if int(dates[data.name_to_id(name)]) < 2005:
            continue
        result.append(path )
    return np.asarray(result)

In [35]:
paths = paths("F:\messy code\\afg ordered\second generation\\faces")

In [37]:
dataset = tf.data.Dataset.from_tensor_slices(paths)

In [39]:
next(iter(dataset))

<tf.Tensor: shape=(), dtype=string, numpy=b'F:\\messy code\\afg ordered\\second generation\\faces\\118x118_to_127x127\\725092char1_face0.jpg'>

In [40]:
feature_dir = "F:\messy code\\afg ordered\second generation\getchu hopefully last\content\\features"
def name_to_picture(path_tensor):
    path = path_tensor.numpy().decode("utf-8")
    image = tf.io.read_file(path)
    image = tf.image.decode_jpeg(image)
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.image.resize(image, [128, 128])

    name = data.path_to_name(path)
    feature_path = data.name_to_feature_path(name , feature_dir)

    feature_vector = np.load(feature_path)

    feature_len = feature_vector.shape[0]

    feature_vector = feature_vector.reshape(1, feature_len)
    return image , feature_vector


dataset = dataset.map(lambda x: tf.py_function(name_to_picture, [x], Tout = [tf.float32, tf.float32]))

In [41]:
next(iter(dataset))

(<tf.Tensor: shape=(128, 128, 3), dtype=float32, numpy=
 array([[[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],
 
        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],
 
        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],
 
        ...,
 
        [[0.9750001 , 0.8443628 

In [42]:
tf.data.DatasetSpec.from_value(dataset)

DatasetSpec((TensorSpec(shape=<unknown>, dtype=tf.float32, name=None), TensorSpec(shape=<unknown>, dtype=tf.float32, name=None)), TensorShape([]))

In [43]:
tf.data.experimental.save(dataset ,'F:\messy code\\afg ordered\second generation' , compression = 'GZIP')